using System.Reflection;
using System.Runtime.CompilerServices;

//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

[assembly: AssemblyTitleAttribute("fcSDK CSharp Web Demo")]
[assembly: AssemblyDescriptionAttribute("fcSDK CSharp Web Demo")]
[assembly: AssemblyCompanyAttribute("Dovetail Software")]
[assembly: AssemblyProductAttribute("fcSDK CSharp Web Demo")]
[assembly: AssemblyVersionAttribute("1.0.*")]
[assembly: AssemblyCopyrightAttribute("Copyright (c) 2004")]
[assembly: AssemblyDelaySignAttribute(false)]
[assembly: AssemblyKeyFileAttribute("")]

